import {ProjectCard, ExperienceCard} from './cards'
import './panels.css'
import DataAnnotation_Logo from '../assets/DataAnnotation_Logo.jpg'

export function ProjectPanel() {
  return (
    <div className= "panels">
        <h2> Projects </h2>
        <ProjectCard image={"noimg"} name={"Proj Name"} desc={"This is a desc"} />
        <ProjectCard image={"noimg"} name={"Proj Name"} desc={"This is a desc"} />
        <ProjectCard image={"noimg"} name={"Proj Name"} desc={"This is a desc"} />
    </div>
  )
}

export function ExperiencePanel() {
  return (
    <div className= "panels">
        <h2> Experience </h2>
        <ExperienceCard 
        image={DataAnnotation_Logo} 
        name={"DataAnnotation"} 
        desc={
          <ul>
            <li>Worked on verifying and optimizing and annotating code that was partially 
                or fully generated by large language models.</li>
            <li>Spanned multiple domains including frontend development in React, 
                backend development in Node.js, Flask, and FastAPI, as well as 
                low-level systems programming in C and C++.</li>
            <li>Identified and corrected logical, structural, and performance related issues to 
                ensure the code was production ready and maintainable.</li>
            <li>Contributed to reinforcement learning workflow with the new refined training data.</li>
          </ul>} />
    </div>
  )
}

export function AboutmePanel() {
  return (
    <div className= "panels panels-small">
        <div className= "Aboutme-title">
        <h3> About Me </h3>
        </div>
        <div className="Aboutme-desc">
          <p1>Im a 4th year Computer Science student at Univ of California, Santa Cruz. 
              My current interests are in Distributed Systems, Operating Systems, Compilers and Backend development.
              Some of my projects are attached below with a live demo or video.</p1>
        </div>
    </div>
  )
}

export function LanguagesPanel() {
  return (
    <div className= "panels panels-small">
        <div className="Skills-desc">
          <div className="Languages">
            <h3>Languages</h3>
              <ul>C</ul>
              <ul>C++</ul>
              <ul>Python</ul>
              <ul>Java</ul>
              <ul>Javascript</ul>
          </div>
          <div className="Frameworks">
            <h3>Frameworks/Tools</h3>
              <ul>Linux</ul>
              <ul>Git</ul>
              <ul>Docker</ul>
              <ul>React</ul>
              <ul>Express</ul>
              <ul>Firebase</ul>
              <ul>Fast API</ul>
              <ul>Flask</ul>
          </div>
          <div className="Skills">
            <h3>Skills</h3>
              <ul>Distributed Systems</ul>
              <ul>Operating Systems</ul>
              <ul>MultiThreading</ul>
              <ul>Compilers</ul>
              <ul>Datastructures</ul>
              <ul>Algorithms and Analysis</ul>
              <ul>Computer Architecture</ul>
              <ul>OOP</ul>
          </div>
        </div>
    </div>
  )
}

