import Accordion from 'react-bootstrap/Accordion';
import '../global.css'
import { useState } from 'react';
import DALogo from '../assets/DataAnnotation_Logo.jpg'

export function Experience() {

  const [activeKey, setActiveKey] = useState("0");
  const handleSelect = (eventKey) => {
    if (eventKey === null) return;
    setActiveKey(eventKey);
  };

  return ( 
    <div className="text-center fs-8 w-80 mt-5 text-light border border border-5 border-dark rounded blur">

        <h3>Experience </h3>

        <Accordion activeKey={activeKey} onSelect={handleSelect}>
        <Accordion.Item eventKey="0">
            <Accordion.Header>
              <img src={DALogo} alt="icon" className="me-2" style={{ width: '30px' }} /> 
                              DataAnnotation - Code Verification
            </Accordion.Header>
            <Accordion.Body className='text-start'>
              <ul>
                <li> Worked on verifying and optimizing and annotating code that was partially or fully generated by large language models. </li>
                <li> Spanned multiple domains including frontend development in React, backend development in Node.js, Flask, and FastAPI, as well as low-level systems programming in C and C++. </li>
                <li> Identified and corrected logical, structural, and performance related issues to ensure the code was production ready and maintainable. </li>
                <li> Contributed to reinforcement learning workflow with the new refined training data. </li>
              </ul>
              <br></br>
            </Accordion.Body>
        </Accordion.Item>
        </Accordion>
    </div>
  )
}
