import Accordion from 'react-bootstrap/Accordion';
import '../global.css'
import { useState } from 'react';
import DALogo from '../assets/DataAnnotation_Logo.jpg'

export function Experience() {

  const [activeKey, setActiveKey] = useState("0");
  const handleSelect = (eventKey) => {
    if (eventKey === null) return;
    setActiveKey(eventKey);
  };

  return ( 
    <div className="text-center fs-8 w-80 mt-5 border border border-5 border-dark rounded blur">

        <h3 className='text-light'>Experience </h3>

        <Accordion activeKey={activeKey} onSelect={handleSelect}>
        <Accordion.Item eventKey="0">
            <Accordion.Header>
              <img src={DALogo} alt="icon" className="me-2" style={{ width: '30px' }} /> 
                              <div className='text-light'> DataAnnotation - Code Verification </div>
            </Accordion.Header>
            <Accordion.Body className='text-start'>
              <ul className='text-light'>
                <li> Verified, optimized and annotated code that was partially or fully generated by large language models. </li>
                <li> Focused on development in React, backend development in Node.js, Flask, and FastAPI, and some low level systems programming in C and C++. </li>
                <li> Corrected structural, and performance issues to ensure the code was production ready and maintainable. </li>
                <li> Contributed to reinforcement learning workflow with the new refined training data. </li>
              </ul>
              <br></br>
            </Accordion.Body>
        </Accordion.Item>
        </Accordion>
    </div>
  )
}
